PRAGMA threads=10;
PRAGMA max_temp_directory_size='10GiB';

CREATE TABLE liquor_sales AS SELECT * FROM 'data\iowa_liquor_sales.csv';

CREATE TABLE liquor_sales_ELT AS SELECT * FROM 'data\iowa_liquor_sales_ETL_ready.csv';

SELECT * FROM liquor_sales_ELT LIMIT 20;

-- COLUMNS NAMES CHANGE
ALTER TABLE liquor_sales RENAME COLUMN "Invoice/Item Number" TO 'INVOICE';
ALTER TABLE liquor_sales RENAME COLUMN "Date" TO 'DATE';
ALTER TABLE liquor_sales RENAME COLUMN "Store Number" TO 'STORE_NUMBER';
ALTER TABLE liquor_sales RENAME COLUMN "Store Name" TO 'STORE_NAME';
ALTER TABLE liquor_sales RENAME COLUMN "Address" TO 'ADDRESS';
ALTER TABLE liquor_sales RENAME COLUMN "City" TO 'CITY';
ALTER TABLE liquor_sales RENAME COLUMN "Zip Code" TO 'ZIP_CODE';
ALTER TABLE liquor_sales RENAME COLUMN "Store Location" TO 'STORE_LOCATION';
ALTER TABLE liquor_sales RENAME COLUMN "County Number" TO 'COUNTY_NUMBER';
ALTER TABLE liquor_sales RENAME COLUMN "County" TO 'COUNTY';
ALTER TABLE liquor_sales RENAME COLUMN "Category" TO 'CATEGORY_NUMBER';
ALTER TABLE liquor_sales RENAME COLUMN "Category Name" TO 'CATEGORY_NAME';
ALTER TABLE liquor_sales RENAME COLUMN "Vendor Name" TO 'VENDOR_NAME';
ALTER TABLE liquor_sales RENAME COLUMN "Vendor Number" TO 'VENDOR_NUMBER';
ALTER TABLE liquor_sales RENAME COLUMN "Item Number" TO 'ITEM_NUMBER';
ALTER TABLE liquor_sales RENAME COLUMN "Item Description" TO 'ITEM_DESCRIPTION';
ALTER TABLE liquor_sales RENAME COLUMN "Pack" TO 'PACK';
ALTER TABLE liquor_sales RENAME COLUMN "Bottle Volume (ml)" TO 'BOTTLE_VOLUME_ML';
ALTER TABLE liquor_sales RENAME COLUMN "State Bottle Cost" TO 'BOTTLE_COST_DOL';
ALTER TABLE liquor_sales RENAME COLUMN "State Bottle Retail" TO 'BOTTLE_RETAIL_DOL';
ALTER TABLE liquor_sales RENAME COLUMN "Bottles Sold" TO 'BOTTLES_SOLD';
ALTER TABLE liquor_sales RENAME COLUMN "Sale (Dollars)" TO 'SALE_DOL';
ALTER TABLE liquor_sales RENAME COLUMN "Volume Sold (Liters)" TO 'VOLUME_SOLD_L';
ALTER TABLE liquor_sales DROP COLUMN "Volume Sold (Gallons)";

--- STORE NAME PADRONIZATION
UPDATE liquor_sales SET STORE_NAME = UPPER(STORE_NAME);

--- ADDRESS PADRONIZATION
UPDATE liquor_sales SET ADDRESS = UPPER(ADDRESS);
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'.', '');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,',', '');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'  ', ' ');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'STREET', 'ST');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'WEST', 'W');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'NORTH', 'N');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'EAST', 'E');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'ROAD', 'RD');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'AVENUE', 'AVE');
UPDATE liquor_sales SET ADDRESS = REPLACE(ADDRESS,'DRIVE', 'DR');

--- CITIES NAMES CORRECTION
UPDATE liquor_sales SET CITY = UPPER(CITY);
UPDATE liquor_sales SET CITY = REPLACE(CITY,'''', '');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'CLEARLAKE', 'CLEAR LAKE');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'DEWITT', 'DE WITT');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'FT. ATKINSON', 'FORT ATKINSON');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'GRAND MOUNDS', 'GRAND MOUND');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'GUTTENBURG', 'GUTTENBERG');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'KELLOG', 'KELLOGG');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'KELLOGGG', 'KELLOGG');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'LECLAIRE', 'LE CLAIRE');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'LEMARS', 'LE MARS');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'MELCHER-DALLAS', 'MELCHER');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'MT VERNON', 'MOUNT VERNON');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'MT PLEASANT', 'MOUNT PLEASANT');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'OTTUWMA', 'OTTUMWA');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'OTUMWA', 'OTTUMWA');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'ST ANSGAR', 'SAINT ANSGAR');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'ST CHARLES', 'SAINT CHARLES');
UPDATE liquor_sales SET CITY = REPLACE(CITY,'ST LUCAS', 'SAINT LUCAS');

--- COUNTY NAMES CORRECTION
UPDATE liquor_sales SET COUNTY = UPPER(COUNTY);
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'BUENA VIST', 'BUENA VISTA');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'BUENA VISTAA', 'BUENA VISTA');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'CERRO GORD', 'CERRO GORDO');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'CERRO GORDOO', 'CERRO GORDO');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'OBRIEN', 'O''BRIEN');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'POTTAWATTA', 'POTTAWATTAMIE');
UPDATE liquor_sales SET COUNTY = REPLACE(COUNTY,'POTTAWATTAMIEMIE', 'POTTAWATTAMIE');

--- CATEGORY NAME
UPDATE liquor_sales SET CATEGORY_NAME = UPPER(CATEGORY_NAME);
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'  ', ' ');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMARETTO - IMPORTED', 'IMPORTED AMARETTO');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMERICAN CORDIALS & LIQUEURS', 'AMERICAN CORDIALS & LIQUEURS');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMERICAN CORDIALS & LIQUEURSS', 'AMERICAN CORDIALS & LIQUEURS');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMERICAN DISTILLED SPIRIT SPECIALTY', 'AMERICAN DISTILLED SPIRITS SPECIALTY');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMERICAN DISTILLED SPIRITSS SPECIALTY', 'AMERICAN DISTILLED SPIRITS SPECIALTY');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'AMERICAN VODKAS', 'AMERICAN VODKA');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'COCKTAILS / RTD', 'COCKTAILS/RTD');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'COCKTAILS /RTD', 'COCKTAILS/RTD');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'FLAVORED GINS', 'FLAVORED GIN');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'HIGH PROOF BEER - AMERICAN', 'AMERICAN HIGH PROOF BEER');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED CORDIALS & LIQUEUR', 'IMPORTED CORDIALS & LIQUEURS');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED CORDIALS & LIQUEURSS', 'IMPORTED CORDIALS & LIQUEURS');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED DISTILLED SPIRIT SPECIALTY', 'AMERICAN DISTILLED SPIRITS SPECIALTY');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED DISTILLED SPIRITSS SPECIALTY', 'AMERICAN DISTILLED SPIRITS SPECIALTY');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED VODKAS', 'IMPORTED VODKA');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED VODKA - CHERRY', 'IMPORTED FLAVORED VODKA');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'IMPORTED VODKA - MISC', 'IMPORTED VODKA');
UPDATE liquor_sales SET CATEGORY_NAME = REPLACE(CATEGORY_NAME,'SCHNAPPS - IMPORTED', 'IMPORTED SCHNAPPS');

--- VENDOR_NAME

UPDATE liquor_sales SET VENDOR_NAME = UPPER(VENDOR_NAME);
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'  ', ' ');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'.', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,',', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' / ', ' ');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' CORPORATION', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' CORP', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' LTD', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' LLC', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' INC', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' JJB', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' LL', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'LLC', '');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,' ET CIE', '');

UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'BLAUM BROS DISTILLING', 'BLAUM BROTHERS DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'BROWN FORMAN', 'BROWN-FORMAN');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'CAMPARI(SKYY)', 'CAMPARI');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'CHATHAM IMPORTSINC', 'CHATHAM IMPORTS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'COOPERSPIRITSINTERNATIONAL', 'COOPER SPIRITS INTERNATIONAL');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'DUGGAN''S DISTILLERS PRODUCTS','DUGGAN''S DISTILLERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'DUGGANS DISTILLERS','DUGGAN''S DISTILLERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'E AND J GALLO WINERY', 'E & J GALLO WINERY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'FRANK LIN DISTILLERS PRO', 'FRANK-LIN DISTILLERS PRODUCTS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'GUNSANDMOREINFO', 'GUNSANDMORE INFO');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'IMPEX BEVERAGE', 'IMPEX BEVERAGES');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'IMPEX BEVERAGESS', 'IMPEX BEVERAGES');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'KINDRED SPIRIT N AMERICA', 'KINDRED SPIRITS OF NORTH AMERICA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'LAIRD AND COMPANY', 'LAIRD & COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MISSISSIPPI RIVER DISTIL', 'MISSISSIPPI RIVER DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MISSISSIPPI RIVER DISTILLINGLING', 'MISSISSIPPI RIVER DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MODERN SPIRIT', 'MODERN SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MODERN SPIRITSS', 'MODERN SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PACIFIC EDGE WINE AND SPIRITS', 'PACIFIC EDGE WINE & SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PARK STREET IMPORTS- CABALLEROS', 'PARK STREET IMPORTS-CABALLEROS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PHILLIPS BEVERAGE', 'PHILLIPS BEVERAGE COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PHILLIPS BEVERAGE COMPANY COMPANY', 'PHILLIPS BEVERAGE COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PRESTIGE WINE AND SPIRITS GROUP', 'PRESTIGE WINE & SPIRITS GROUP');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'REMYINTREAU USA', 'REMY COINTREAU USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'RUSSIAN STANDARD VODKA', 'RUSSIAN STANDARD VODKA USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'RUSSIAN STANDARD VODKA USA USA', 'RUSSIAN STANDARD VODKA USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SHAW-ROSS INTERNATIONAL', 'SHAW-ROSS INTERNATIONAL IMPORTERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SHAW ROSS INTERNATIONAL IMPORTERS LL', 'SHAW-ROSS INTERNATIONAL IMPORTERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SIDNEY FRANK IMPORTING', 'SIDNEY FRANK IMPORTING COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SIDNEY FRANK IMPORTING COMPANY', 'SIDNEY FRANK IMPORTING COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'ST GEORGE SPIRIT', 'ST GEORGE SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'ST GEORGE SPIRITSS', 'ST GEORGE SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'W J DEUTSCH AND SONS', 'W J DEUTSCH & SONS'); 
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'WHYTE AND MACHAY(AMERICAS) LIMITEDL', 'WHYTE AND MACHAY (AMERICAS)');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'WILLIAM GRANT AND SONS', 'WILLIAM GRANT & SONS');

COPY (SELECT * FROM liquor_sales) TO 'data/iowa_liquor_sales_ETL_phase_1.csv' WITH (HEADER, DELIMITER ',');