PRAGMA threads=10;
PRAGMA max_temp_directory_size='10GiB';

CREATE TABLE liquor_sales AS SELECT * FROM 'data\iowa_liquor_sales_ETL_phase_1.csv';

SELECT * FROM liquor_sales LIMIT 20;

ALTER TABLE liquor_sales ADD COLUMN YEAR INTEGER;
ALTER TABLE liquor_sales ADD COLUMN MONTH INTEGER;
ALTER TABLE liquor_sales ADD COLUMN DAY INTEGER;

UPDATE liquor_sales
SET
    YEAR = EXTRACT(YEAR FROM DATE),
    MONTH = EXTRACT(MONTH FROM DATE),
    DAY = EXTRACT(DAY FROM DATE);

UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'BLAUM BROS DISTILLING', 'BLAUM BROTHERS DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'BROWN FORMAN', 'BROWN-FORMAN');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'CAMPARI(SKYY)', 'CAMPARI');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'CHATHAM IMPORTSINC', 'CHATHAM IMPORTS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'COOPERSPIRITSINTERNATIONAL', 'COOPER SPIRITS INTERNATIONAL');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'DUGGAN''S DISTILLERS PRODUCTS','DUGGAN''S DISTILLERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'DUGGANS DISTILLERS','DUGGAN''S DISTILLERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'E AND J GALLO WINERY', 'E & J GALLO WINERY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'FRANK LIN DISTILLERS PRO', 'FRANK-LIN DISTILLERS PRODUCTS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'GUNSANDMOREINFO', 'GUNSANDMORE INFO');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'IMPEX BEVERAGE', 'IMPEX BEVERAGES');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'IMPEX BEVERAGESS', 'IMPEX BEVERAGES');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'KINDRED SPIRIT N AMERICA', 'KINDRED SPIRITS OF NORTH AMERICA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'LAIRD AND COMPANY', 'LAIRD & COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MISSISSIPPI RIVER DISTIL', 'MISSISSIPPI RIVER DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MISSISSIPPI RIVER DISTILLINGLING', 'MISSISSIPPI RIVER DISTILLING');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MODERN SPIRIT', 'MODERN SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'MODERN SPIRITSS', 'MODERN SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PACIFIC EDGE WINE AND SPIRITS', 'PACIFIC EDGE WINE & SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PARK STREET IMPORTS- CABALLEROS', 'PARK STREET IMPORTS-CABALLEROS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PHILLIPS BEVERAGE', 'PHILLIPS BEVERAGE COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PHILLIPS BEVERAGE COMPANY COMPANY', 'PHILLIPS BEVERAGE COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'PRESTIGE WINE AND SPIRITS GROUP', 'PRESTIGE WINE & SPIRITS GROUP');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'REMYINTREAU USA', 'REMY COINTREAU USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'RUSSIAN STANDARD VODKA', 'RUSSIAN STANDARD VODKA USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'RUSSIAN STANDARD VODKA USA USA', 'RUSSIAN STANDARD VODKA USA');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SHAW-ROSS INTERNATIONAL', 'SHAW-ROSS INTERNATIONAL IMPORTERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SHAW ROSS INTERNATIONAL IMPORTERS LL', 'SHAW-ROSS INTERNATIONAL IMPORTERS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SIDNEY FRANK IMPORTING', 'SIDNEY FRANK IMPORTING COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'SIDNEY FRANK IMPORTING COMPANY', 'SIDNEY FRANK IMPORTING COMPANY');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'ST GEORGE SPIRIT', 'ST GEORGE SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'ST GEORGE SPIRITSS', 'ST GEORGE SPIRITS');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'W J DEUTSCH AND SONS', 'W J DEUTSCH & SONS'); 
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'WHYTE AND MACHAY(AMERICAS) LIMITEDL', 'WHYTE AND MACHAY (AMERICAS)');
UPDATE liquor_sales SET VENDOR_NAME = REPLACE(VENDOR_NAME,'WILLIAM GRANT AND SONS', 'WILLIAM GRANT & SONS');


COPY (SELECT * FROM liquor_sales) TO 'data/iowa_liquor_sales_ETL_OK.csv' WITH (HEADER, DELIMITER ',');